steps:
# 1) build docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/orbi-city-website:$BUILD_ID', '.']

# 2) push image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/orbi-city-website:$BUILD_ID']

# 3) deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - orbi-city-website
    - --image
    - gcr.io/$PROJECT_ID/orbi-city-website:$BUILD_ID
    - --region
    - europe-west1
    - --platform
    - managed
    - --allow-unauthenticated
    - --set-env-vars
    - NODE_ENV=production,PORT=8080
images:
- 'gcr.io/$PROJECT_ID/orbi-city-website:$BUILD_ID'
timeout: 1200s
