substitutions:
  _REGION: "europe-west1"
  _REPOSITORY: "orbi-city-docker"

timeout: "1200s"

steps:
- id: "build_and_push"
  name: "gcr.io/cloud-builders/docker"
  entrypoint: "bash"
  args:
    - "-c"
    - |
      set -euo pipefail
      # choose tag: prefer SHORT_SHA (triggered builds). If absent, use BUILD_ID.
      TAG="${SHORT_SHA:-${BUILD_ID}}"
      IMAGE="europe-west1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/orbi-city-website:${TAG}"
      echo "Building image $IMAGE"
      docker build -t "$IMAGE" -f Dockerfile .
      echo "Pushing image $IMAGE"
      docker push "$IMAGE"
      echo "$IMAGE" > /workspace/image.txt

- id: "deploy"
  name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "bash"
  args:
    - "-c"
    - |
      set -euo pipefail
      IMAGE=$(cat /workspace/image.txt)
      echo "Deploying $IMAGE to region ${_REGION}"
      gcloud run deploy orbi-city-website \
        --image="$IMAGE" \
        --region="${_REGION}" \
        --platform=managed \
        --allow-unauthenticated \
        --set-env-vars=NODE_ENV=production,PORT=8080

# optional artifact list
# images:  <-- omitted because we compute tag inside bash and echo it to workspace.
